name: Auto Push Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push if changes exist
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-commit changes" && git push)
